# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='user_email',
            field=models.CharField(default=b'false', max_length=50),
        ),
    ]
